# The Edge

The night was dark and the breeze was cold, much like the void in what was once her heart. Now there was just the ghost---as seen in her eyes. Had she hurried into it? Had she thought it through? Had she been forced into it? She didn't quite know. A lot had happened over the last few months---a lot more than she thought she could comprehend. It had all started with that moment---the impulse.

She looked around the now-empty open cafeteria. It was 23:45. She smiled at her Nexus. Wasn't this the device responsible for half her troubles; the device that had started it all? How it looked so innocent while displaying those numbers in a delicate font, she thought. The word, "font", reminded her of her brother---he was obsessive about writing, fonts and style even though he knew not much about them. It was funny when people tried. No, this wasn't the time to think of those things.

Straightening her face, she looked around to make sure the sandwich stall guys were busy with their numbers. Her black clothes provided her with the best possible camouflage for her surroundings. Like a shadow, she moved over to the railing that was about two metres away from the parapet. She held the railing, feeling the cold metal. She remembered her brother say, 'I like the statement "This too shall pass." One should remember that.' At least he knew how to move on. Or perhaps not.

She climbed over the railing, defying the disadvantage that her height was. Perhaps grave situations brought out a different self in people. Walking over to the parapet against the instruction to not cross the railing, she felt a thrill. Was this the same feeling that had brought her to this day? A cold breeze blew, making her realise that she was over forty metres above the ground. She moved towards the west, behind a few stalls, so no one from the inside of the building could see her. She wanted peace for once. The voices in her head were killing her.

She climbed the parapet and took in the view. Yes, she was a bit of an adrenaline junkie, but not to this extent. She was here for a different purpose, driven mostly by gloom. It was now time for the toughest part. She remembered her mother, a woman who'd shown immense courage and seen death in the face twice in her life, spat on its face and returned. She welled up, even though she thought her eyes had dried of all the crying she'd done over the last few weeks. Did she not have the courage to go through what she was going through, or was it not worth it? That debate hadn't quite gotten over.

She walked to the edge. A gush of wind, and that's all it would take for gravity to show how heartless it was. Although, that didn't scare her. Heartlessness wasn't a stranger to her anymore. She'd seen enough of it, and one more was no big deal. She closed her eyes, not out of the fear of what was to happen, but to concentrate on the war inside, rather than the serenity of the night. She'd begun the war, and forty metres was a distance she was more than willing to go, to see it end.
