# The Stain

Perched precariously on} the parapet, she closed her eyes. A drop of tear rolled off her cheek, missed her toe, and fell the forty metres, getting lost in the darkness. Solace evaded her every moment, and she was getting nowhere close to a solution to this. After all, the past cannot be changed. Her brother had asked her to move on, think straight and leave what wasn't good for her. She wanted to listen to him; she knew he was right. But there was this nagging feeling in her that wouldn't go, and the pain---both physical and emotional---tortured her, every waking moment. Sleep was no comfort either, her dreams tormented her no less. She'd withdrawn herself from the rest of the world, and people had started noticing the absence. On the one hand, everyone wanted to know if they could help her, and on the other, they hated her for the fact that she was almost always unavailable for anything.

The loneliness in her life had become unbearable. Her life was changing at rates she had never imagined. Her body and mind could only go through so much. It was perhaps time to end it all---she'd committed a _sin_, and this was probably how God punished her: by making her live the life she dreaded, by making her go through all that she'd feared. One couldn't help but notice the irony in the situation she was in. Goa, the place she'd loved, now seemed like a terror destination to her.

Cold November rain fell on her, waking her up from her reverie. Her ghostly eyes that had swollen of crying, moved around sluggishly as she tried to gather her senses. She'd missed thirteen calls from her colleagues. She didn't bother to return them. She wouldn't have to see their faces anymore, anyway. She slid the phone into her pocket as if it were the one thing that she wanted to protect from the rain. Who was to talk logic to a person who saw no light at the end of the tunnel? Would it even matter to them?

At least, at this time, she could be herself. There had been enough fake smiling and fake laughing; there had been enough of the fake life she'd been living of late. She missed the time she could just about suddenly gather a score of people and start some fun activity at work, or organise a dance competition, or make people play one-minute games. It was strange how things had turned upside down in a matter of seconds. A part of her told her it wasn't her fault, and that she should stop blaming herself. But then, the other side which detested her had an equally strong point to blame her.

Life is weird. Sometimes, even though you want to die, you choose to live. You fight the war, no matter how many corpses you see, no matter how terrified you are of your own end, how confident---or doubtful---you are of whether it's worth it. You fight in spite of knowing that once a war began, it always drew souls out of bodies---be it a war between two countries, two people, or your own two selves. But this time, she was determined not to let life have its way. She wanted it all to end tonight; there had been enough bloodshed already.

There was nobody she could go to, no arms that could wrap her and tell her it was all going to be OK. This was something she would have to take to her grave, the grave that she'd soon reach. She slid her hand into her pocket and brought out a piece of white cloth that had a blackish blotch on it. She broke down as she brought it to her lips. Moments passed. She stopped, gathered herself, took a deep breath, and closed her eyes again.

She thought of her mother's eyes that portrayed care and courage at the same time, her father's face that had the uncanny kindness towards his little girl, and her dear sister who had been by her side all the time, no matter what, until she'd gotten married and moved out. She was the one person she had, from whom she could learn so much from, someone she could look up to, and the one she could always fall back to, no matter what disaster looked her in the eye. She then remembered her brother---her cousin---who seemed cold-hearted on the outside, but almost always had a logical explanation for everything. It was sad that she couldn't discuss this particular situation of hers with him. She thought of their lives without her. She saw the devastated look on their faces when she arrived at her door---lifeless, wrapped in white sheets, face distorted but sewn in place. She saw her own face---it held no expression. It may have been because of the way it was sewn, but no expression nonetheless. She thought it was eternal bliss that seemed like lifelessness. And then her train of thought went back to the day she'd ridden on the Mysore Road---_eternal bliss_.

She closed her eyes. She heard the rain fall on the roofs all around, and on her scalp and her shoulders, and then on her forehead. There was absolute silence otherwise. Her head wasn't buzzing anymore. All she could hear, after a few seconds, was a thud in her head as she woke up with a shudder, while at the same time, another shadow walked in, grabbed her by both her upper arms, and helped her across the parapet whose edge she was now sitting at, into the cafeteria, with a pair of terrified eyes.
