# The Debate

All the while that Frieda sat on the south-west side of the cafeteria, what she hadn't noticed was another shadow, stretching his legs in the north-east corner of it, in the dark, by the table closest to the hand wash area. It was very unusual for him to have been there at the time. His work hours ended at 18:00. An hour of gym burning time along with calories, and then an hour of table tennis made up his evening routine. Tonight, he'd been to the cafeteria and sat there, reflecting upon a couple of the hundreds of things he'd wanted to form opinions on, until 22:00 or so when he'd dozed off.

The sound of a crashing thunderbolt had woken him up. He'd seen a girl enter the open wing from the other door, a few metres away, walk across with a bunch of tissues in her hand, sniffing. He'd first thought she'd perhaps caught a cold, and had come out to get some fresh air. _Whatever..._ He'd laid his head down again.

He woke up after a while, unsure what had disturbed his sleep, thankful in a way nonetheless. He checked his watch and realised that his nap had been quite a long one to be taken on a series of the café chairs. He stood up, silently pushing his chair, preparing to leave for the day. While in the process, he looked around to take in the view of the empty cafeteria. It was unusually empty---he'd always seen the place overflowing with people. Of course, that was until 18:00 every day. He spotted a familiar shadow. _Is this the same girl?_ He checked his watch again. _OK, something's not right._ She had gone across the railing. This was unusual. People who worked there never crossed the railing and went to the parapet. It was against the safety guidelines.

He did not believe in suicide. He was unsure it was the way to go. He'd been told when he was a kid, that a person didn't have the right to end his life just as he did not have control over the decision to begin his life. This hadn't made sense to him---why, it was one of the most absurd things he'd ever heard---yet, he'd accepted it anyway. This had sat in his head for years without any thought, and he'd stuck on to it like a principle. He had nothing against suicide, except the simple thought that it affected many people and not just the person who died. And, of course, that it was sad. Or did it somehow seem morally wrong to him, though he couldn't explain it? 'If death's the answer, why be born in the first place', was his (perhaps equally absurd) response, when anyone mentioned suicide in a conversation. Tonight he wasn't sure of his standpoint.

_Shut up, not the time!_

He couldn't see someone end her life in front of him. It would scar him for life, not to mention the legal liabilities. He didn't want to startle her in the middle of the night---she may have thought she was alone. He crossed the railing next to the wash area---a few metres from where he was---and then walked along the parapet. The rain was quite heavy now, and he was sure she couldn't hear him walk, given the sound of the rain, and her mental state.

She hung her face, closed her eyes. She sat still. _This is the sign. Faster!_ There was not much time to think about the noise of his feet splashing water. He went right next to her and grabbed her by both her upper arms. He thought she'd shuddered, but wasn't sure it was because of him.

Not seeming startled, she turned her face to him. Her eyes were dry and ghostly, almost hollow. It was a strange expression---_the expression of inner death_. He'd only heard of them from his grandmother and from people like her, who seemed to know everything about what was going on in everyone's head. The girl made no attempt to wriggle away. It was disturbing. He didn't know what he was thinking---whether he was unsure if her jumping would make any difference at all, or wanted to know what had led to a girl to come to this conclusion---he was confused.

He gestured to the girl to come into the cafeteria rather than hang her feet the other way. Frieda, seeing no sign of hostility---not that it mattered---obliged, and jumped into the area between the parapet and the railing.

'Nothing is worth it', he whispered to her.

She just stood there, with no change in her expression, unmindful of the lashing rain. He let go of her arms, turned around, and made his way to the door. He wanted to go home and sleep---it had been a weird day. She turned around and stood by the parapet looking out into the night.
