# The Decision

As the skies roared, she stood there, thinking of the day he’d fallen. Tears streamed down her face. It was all her fault, she thought, that one of the most remarkable men she’d met had ceased to exist. Life was no more what she thought it was. She’d sinned by attempting suicide. She’d been taught when she was a child that it was sinful to try to claim rights over what belonged to God. Life belonged to God, and it was His decision when to take it back. She’d tried to take her life once and she’d been punished with the guilt that killed her, and the lifelong void that his absence had created. And now here she was, trying to do just that, yet again.

Her thoughts shifted to the dreadful day, about a month ago. Why did she have to start the topic when they’d both taken mental notes not to talk about all that during the trip? Why did she have to try to stab herself? What was she thinking? How could a pocket fruit knife inflict enough damage to the abdomen to kill someone? And why did she have to run!

She remembered the shock of when her mind had finally come out of denial after a few hours that she’d sat on the rock that she’d hit, holding her lower abdomen---the rock that had saved her, but killed him. She’d brushed her clothes and walked to the cliff to see if there was still hope. There hadn’t seemed to be any; he seemed to have gone for good. She’d slowly clambered down the cliff, a few metres, hoping to find him. She’d had to stop once she’d hit a shelf that had a little shrub which held a piece of what seemed like his white t-shirt. It had a stain of blood on it. She hadn’t been sure it was his, but then she’d thought the blood had seemed fresh, and it was a piece of white t-shirt cloth---he too had worn a white tee that day. It couldn’t have been anyone’s but his.

She was scared no more. The worst had already happened. She then had had a change of mind; she’d wanted to go back to Bangalore. She hadn’t been able to think of anything beyond that. One thing that she’d wanted to do was meet his parents, just to see their faces, while they were still under the impression that their son was alive. A part of her still hadn’t wanted to believe that he was no more.

Climbing up that cliff had been one of the most difficult tasks she’d done, ever. She’d lost count of how many times she’d slipped, and hoped to fall off and die. But she'd stuck to her decision and continued to climb. _Life has its strange ways._

She’d picked up her rucksack and walked towards the village. She’d spent the night under a tree. A kind woman had come to her in the morning and offered her some porridge. Having eaten that, and having forgotten for the moment, about all the losses she’d incurred, she’d headed over to the Kulem railway station and waited for the Vasco-da-Gama -- Bengaluru Link Express to arrive.

She’d travelled sitting next to the restrooms in one of the sleeper coaches. She’d left his rucksack near the falls. She hadn’t wanted to carry anything that belonged to him, except for some reason, the piece of cloth that she’d retrieved from the shrub as his final remnants. She, however, hadn’t dared take it out, lest she got wrong thoughts. The TTE, looking at her condition, hadn’t asked her for tickets or her identity; she’d looked terrible---torn to shreds. At least, these strangers were being kind to her.

He wouldn’t have wanted her to die, she thought. He’d died trying to save her! She couldn’t let him down that way. She had to live. She had to live, no matter how much the guilt ate away at her. She thought that she had to pay him back by looking out for his parents whenever they needed help, by doing everything he would’ve, had he been alive.
```{r echo=FALSE}
scenebreak()
```
People had started looking for him now. Nobody had any idea where he was. She’d met his parents on Sunday evening after she’d returned. They’d told her that Friedrich had been somewhere with his work friends and that he’d be back by the next morning. It had taken her all her strength to control herself when they’d said that with a smile. It had stabbed her in the chest. She’d run out of the house citing some work emergency. That day she’d cried a river. Two days later, she’d gotten a call from his mother asking her if she’d heard from him after the weekend. Of course, she hadn’t heard from him.

A couple of weeks later, his parents had received a call from the local police station asking them to identify a set of clothes and a bag with miscellany. It had broken them down. All they could do was meekly thank the trio of trekkers who’d come all the way down to Bangalore to see to that the things had reached his parents. The trekkers, one of whom was a forensic analyst, had told them in the most graceful manner possible that there were skid marks near the cliff that indicated that a person of about 70~kg had fallen off it, and that judging by the fall, he couldn’t have survived. She’d promised them to be there for them anytime they wanted.

She turned away from the parapet. Somehow, she wanted the war to go on. She didn’t care much for anything else. She remembered Herodotus: _When life is so burdensome, death has become for man a sought-after refuge._ Although, refuge wasn’t what she wanted at the moment. It took her some will to decide against walking to the parapet. She had to live, albeit as a merely physical presence. She fought the side of her head that wanted death---an end to this battle---and approached the railing. She reached it and held the metal rod. This was the second time in the night that she’d held it and felt the coldness. _This cold cruelty is the only thing that’s certain._ She stood there, thinking how her emotional turmoil had made her forget that she was now technically a criminal. For a second, she thought of turning back to the parapet. She couldn’t live with that kind of an identity. Her conscience had picked up on it and was poised to kill her. She cried for mercy. She prayed for forgiveness. If only a bolt of lightning struck her and fried her dead!
