# Thank you {-}

_The Damp Roman Candle_ started with a small piece of narration of about a dozen paragraphs, which you'll find to be the first chapter of this story. The passage was written for my blog on a night when I felt creative; it was originally called, _The Damp Roman Candle_. It grew into two chapters, and then three. During the very next weekend, upon insistence by a few of my friends, I wrote the next three chapters. I did not know how long the story would go; I enjoyed writing it, and my friends were kind enough to say they enjoyed reading it. A few weeks later, it became what you just read---this humble, six-chapter-long novelette. It was published to the Kindle Store a few weeks later, with the name of the first chapter changed.

If you liked the work and would like to buy me a cup of coffee, please consider buying the book from the Kindle Store.

I'd like to thank you for the time you allocated to reading this piece. Please feel free to share your feedback, perhaps share a writing tip or something. I hope to learn from your constructive criticism.
